### ISSUE TITLE
CUDA environment is broken when I run a docker container with rocker

### ISSUE THREAD

**Issue by yukke42** [autowarefoundation/autoware#402]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

When I run a docker container built on this repository with rocker, `nvidia-smi` and CUDA packages of autoware.universe didn't work.

### Expected behavior

```
$ rocker --nvidia --x11 --user ghcr.io/autowarefoundation/autoware-universe:humble-latest nvidia-smi
```

returns the same result as 

```
docker run --rm -it --gpus all -e DISPLAY -e TERM -e QT_X11_NO_MITSHM=1 -v /tmp/.X11-unix:/tmp/.X11-unix -v /etc/localtime:/etc/localtime:ro ghcr.io/autowarefoundation/autoware-universe:humble-latest
```

### Actual behavior

```
$ rocker --nvidia --x11 --user --volume $PWD:$HOME/autoware -- ghcr.io/autowarefoundation/autoware-universe:humble-latest nvidia-smi
...
bash: nvidia-smi: command not found
```

or 

```
# in the docker container
$ ros2 launch lidar_centerpoint lidar_centerpoint.launch.xml
[INFO] [launch]: All log files can be found below /home/yusuke/.ros/log/2022-05-27-18-24-13-889706-yusuke-desktop-14888
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [lidar_centerpoint_node-1]: process started with pid [14889]
[lidar_centerpoint_node-1] terminate called after throwing an instance of 'thrust::system::detail::bad_alloc'
[lidar_centerpoint_node-1]   what():  std::bad_alloc: cudaErrorInsufficientDriver: CUDA driver version is insufficient for CUDA runtime version
[ERROR] [lidar_centerpoint_node-1]: process has died [pid 14889, exit code -6, cmd '/home/yusuke/autoware/install/lidar_centerpoint/lib/lidar_centerpoint/lidar_centerpoint_node --ros-args -r __node:=lidar_centerpoint --params-file /tmp/launch_params__7bviznb --params-file /tmp/launch_params_xhbpo0pj --params-file /tmp/launch_params_3cva1bu7 --params-file /tmp/launch_params_591wukuf --params-file /tmp/launch_params_binyjp_2 --params-file /tmp/launch_params_d_ubfmz8 --params-file /tmp/launch_params_3ciwtkcg --params-file /tmp/launch_params_cy1qmkld --params-file /home/yusuke/autoware/install/lidar_centerpoint/share/lidar_centerpoint/config/default.param.yaml -r ~/input/pointcloud:=/sensing/lidar/pointcloud -r ~/output/objects:=objects'].
```

### Steps to reproduce

1. build a docker image in `docker` directory
2. run a docker container with rocker
3. `nvidia-smi`

**Comment by LevieSun** [comment]
I get the same problem

**Comment by kenji-miyake** [comment]
I think this will be resolved after we change the base image to [11.7.0-devel-ubuntu22.04](https://hub.docker.com/layers/cuda/nvidia/cuda/11.7.0-devel-ubuntu22.04/images/sha256-16c790bc3349d70a0416cf8bf1eef9b40433ee907018b5ea32bdbddf75433a9d?context=explore).

But to do that, the network installation packages of cuDNN and TensorRT should be released.
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/

I'm waiting for that.
Or if there is another better approach, I can try it out.

**Comment by LevieSun** [comment]
> I think this will be resolved after we change the base image to [11.7.0-devel-ubuntu22.04](https://hub.docker.com/layers/cuda/nvidia/cuda/11.7.0-devel-ubuntu22.04/images/sha256-16c790bc3349d70a0416cf8bf1eef9b40433ee907018b5ea32bdbddf75433a9d?context=explore).
> 
> But to do that, the network installation packages of cuDNN and TensorRT should be released. https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/
> 
> I'm waiting for that. Or if there is another better approach, I can try it out.

Do you have any other method to solve this problem?

**Comment by kenji-miyake** [comment]
Regarding `nvidia-smi`, I guess it's fixed by installing `nvidia-utils`.

```sh-session
$ apt-file search $(which nvidia-smi)
nvidia-340: /usr/bin/nvidia-smi
nvidia-utils-390: /usr/bin/nvidia-smi
nvidia-utils-418-server: /usr/bin/nvidia-smi
nvidia-utils-435: /usr/bin/nvidia-smi
nvidia-utils-440: /usr/bin/nvidia-smi
nvidia-utils-450-server: /usr/bin/nvidia-smi
nvidia-utils-460-server: /usr/bin/nvidia-smi
nvidia-utils-470: /usr/bin/nvidia-smi
nvidia-utils-470-server: /usr/bin/nvidia-smi
nvidia-utils-510: /usr/bin/nvidia-smi
nvidia-utils-510-server: /usr/bin/nvidia-smi
```

Regarding `cudaErrorInsufficientDriver`, I'm sorry but I'm not sure. :pleading_face: 
I need to investigate the issue to catch up.

**Comment by may012345** [comment]
> Regarding `nvidia-smi`, I guess it's fixed by installing `nvidia-utils`.
> 
> ```
> $ apt-file search $(which nvidia-smi)
> nvidia-340: /usr/bin/nvidia-smi
> nvidia-utils-390: /usr/bin/nvidia-smi
> nvidia-utils-418-server: /usr/bin/nvidia-smi
> nvidia-utils-435: /usr/bin/nvidia-smi
> nvidia-utils-440: /usr/bin/nvidia-smi
> nvidia-utils-450-server: /usr/bin/nvidia-smi
> nvidia-utils-460-server: /usr/bin/nvidia-smi
> nvidia-utils-470: /usr/bin/nvidia-smi
> nvidia-utils-470-server: /usr/bin/nvidia-smi
> nvidia-utils-510: /usr/bin/nvidia-smi
> nvidia-utils-510-server: /usr/bin/nvidia-smi
> ```
> 
> Regarding `cudaErrorInsufficientDriver`, I'm sorry but I'm not sure. 🥺 I need to investigate the issue to catch up.
I also encontered the similar problem. When I run "colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release" in the container of "ghcr.io/autowarefoundation/autoware-universe:latest" image  , I found "CUDA_TOOLKIT_ROOT_DIR not found or specified
CUDA NOT FOUND
TensorRT is NOT Available
CUDNN is NOT Available" error. It seems the container could not find CUDA. How do I fix this problem? Do I need to install autoware from the source instead of the docker?

**Comment by may012345** [comment]
> Regarding `nvidia-smi`, I guess it's fixed by installing `nvidia-utils`.
> 
> ```
> $ apt-file search $(which nvidia-smi)
> nvidia-340: /usr/bin/nvidia-smi
> nvidia-utils-390: /usr/bin/nvidia-smi
> nvidia-utils-418-server: /usr/bin/nvidia-smi
> nvidia-utils-435: /usr/bin/nvidia-smi
> nvidia-utils-440: /usr/bin/nvidia-smi
> nvidia-utils-450-server: /usr/bin/nvidia-smi
> nvidia-utils-460-server: /usr/bin/nvidia-smi
> nvidia-utils-470: /usr/bin/nvidia-smi
> nvidia-utils-470-server: /usr/bin/nvidia-smi
> nvidia-utils-510: /usr/bin/nvidia-smi
> nvidia-utils-510-server: /usr/bin/nvidia-smi
> ```
> 
> Regarding `cudaErrorInsufficientDriver`, I'm sorry but I'm not sure. 🥺 I need to investigate the issue to catch up.

I also encontered the similar problem. When I run "colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release" in the container of "ghcr.io/autowarefoundation/autoware-universe:latest" image , I found "CUDA_TOOLKIT_ROOT_DIR not found or specified
CUDA NOT FOUND
TensorRT is NOT Available
CUDNN is NOT Available" error. It seems the container could not find CUDA. How do I fix this problem? Do I need to install autoware from the source instead of the docker?

**Comment by kenji-miyake** [comment]
@may012345 Seeing @yukke42 -san's comment, I guess you can run Autoware using pure `Docker`, not `rocker`.

**Comment by yukke42** [comment]
Yes. I could run autoware with a`docker run` command and a image built locally following the official tutorial.

```
docker run --rm -it --gpus all -e DISPLAY -e TERM -e QT_X11_NO_MITSHM=1 -v /tmp/.X11-unix:/tmp/.X11-unix -v /etc/localtime:/etc/localtime:ro ghcr.io/autowarefoundation/autoware-universe:humble-latest
```

**Comment by may012345** [comment]
> 

I run with "rocker --nvidia --x11 --user --volume $HOME/autoware -- ghcr.io/autowarefoundation/autoware-universe:latest" and met the problem.

**Comment by may012345** [comment]
> @may012345 Seeing @yukke42 -san's comment, I guess you can run Autoware using pure `Docker`, not `rocker`.

I run with "rocker --nvidia --x11 --user --volume $HOME/autoware -- ghcr.io/autowarefoundation/autoware-universe:latest" and met the problem.
